INSERT INTO instituicaos (instituicao, sigla_instituicao) VALUES
    ('Associação Catarinense de Ensino','ACE'),
    ('Associação das Escolas Reunidas','Asser'),
    ('Associação de Educação e Cultura do Norte Paulista','Fanorp'),
    ('Associação de Ensino Superior de Alagoas','Aesa'),
    ('Associação de Ensino Superior de Olinda','Aeso'),
    ('Associação de Ensino Superior do Piauí','Aespi'),
    ('Associação Educacional de Vitoria','AEV'),
    ('Associação Educacional do Vale do Itajaí-Mirim','Assevim'),
    ('Associação Educacional Dom Bosco','AEDB'),
    ('Associação Paraibana de Ensino Renovado','Asper'),
    ('Autarquia do Ensino Superior de Garanhuns','Aesga'),
    ('Celer Faculdades Ltda','Celer'),
    ('Centre de Educação Superior Reinaldo Ramos','Cesrei'),
    ('Centro de Educação Superior','Única'),
    ('Centro de Educação Superior Norte','Cesnor'),
    ('Centro de Ensino Superior Anísio Teixeira','Cesat'),
    ('Centro de Ensino Superior de Juiz de Fora','CES/JF'),
    ('Centro de Ensino Superior de Maringá','Cesumar'),
    ('Centro de Ensino Superior de Santa Catariana','Cesusc'),
    ('Centro de Ensino Superior de Vitória','Cesv'),
    ('Centro de Ensino Superior do Amapá','Ceap'),
    ('Centro de Ensino Superior do IPE','Unipe'),
    ('Centro de Ensino Superior do Paraná','Cespar'),
    ('Centro de Ensino Superior dos Campos Gerais','Cescage'),
    ('Centro de Ensino Unificado de Teresina','Ceut'),
    ('Centro de Ensino Unificado do Maranhão','Ceuma'),
    ('Centro de Estudos Superiores de Maceió','Cesmac'),
    ('Centro de Extensão Universitária','CEU'),
    ('Centro Federal de Educação Tecnológica de Goiás','Cefetgo'),
    ('Centro Integrado de Ensino Superior do Amazonas','Ciesa'),
    ('Centro Sulamericano de Ensino Superior','Cesul'),
    ('Centro Superior de Vila Velha','UVV'),
    ('Centro Universitario Franciscano de Santa Maria','Unifra'),
    ('Centro Universitário 7 de Setembro','FA7'),
    ('Centro Universitário Adventista de São Paulo','Unasp'),
    ('Centro Universitário Anhanguera de Campo Grande','Unaes'),
    ('Centro Universitário Anhanguera de Santo André - FSA','Anhanguera - FSA'),
    ('Centro Universitário Augusto Motta','Unisuam'),
    ('Centro Universitário Barão de Mauá','CBM'),
    ('Centro Universitário Belas Artes','Belasartes'),
    ('Centro Universitário Carioca','UniCarioca'),
    ('Centro Universitário Católico Salesiano Auxilium','Unisalesiano'),
    ('Centro Universitário Cândido Rondon','Unirondon'),
    ('Centro Universitário Celso Lisboa','Ceucel'),
    ('Centro Universitário Central Paulista','Unicep'),
    ('Centro Universitário Curitiba','Unicuritiba'),
    ('Centro Universitário da Cidade','UniverCidade'),
    ('Centro Universitário da FEI','FEI'),
    ('Centro Universitário da Fundação Assis Gurgacz','FAG'),
    ('Centro Universitário da Fundação Assis Gurgacz - Campus Toledo','FAG-Toledo'),
    ('Centro Universitário da Fundação Educacional Guaxupé','Unifeg'),
    ('Centro Universitário da Grande Dourados','Unigran'),
    ('Centro Universitário das Faculdades Associadas de Ensino','FAE'),
    ('Centro Universitário de Araraquara','Uniara'),
    ('Centro Universitário de Araras','Unar'),
    ('Centro Universitário de Barra Mansa','UBM'),
    ('Centro Universitário de Belo Horizonte','Uni-BH'),
    ('Centro Universitário de Brasília','Uniceub'),
    ('Centro Universitário de Campo Grande','Unaes'),
    ('Centro Universitário de Ensino Superior do Amazonas','Ciesa'),
    ('Centro Universitário de Franca','Uni-Facef'),
    ('Centro Universitário de Goiás','Uni-Anhanguera'),
    ('Centro Universitário de Jaraguá do Sul','Unerj'),
    ('Centro Universitário de Lavras','Unilavras'),
    ('Centro Universitário de Maringá','Ceumar'),
    ('Centro Universitário de Patos de Minas','Unipam'),
    ('Centro Universitário de Rio Preto','Unirp'),
    ('Centro Universitário de São José do Rio Preto','Unirp'),
    ('Centro Universitário de União da Vitória','Uniuv'),
    ('Centro Universitário de Volta Redonda','Unifoa'),
    ('Centro Universitário de Votuporanga','Unifev'),
    ('Centro Universitário Dinâmica das Cataratas','UDC'),
    ('Centro Universitário do Estado do Pará','Cesupa'),
    ('Centro Universitário do Leste de Minas Gerais','Unileste'),
    ('Centro Universitário do Maranhão','Uniceuma'),
    ('Centro Universitário do Norte','Uninorte'),
    ('Centro Universitário do Sul de Minas','Unismg'),
    ('Centro Universitário do Triângulo','Unit'),
    ('Centro Universitário do Vale do Ipojuca','Favip'),
    ('Centro Universitário dos Guararapes','UNIFG'),
    ('Centro Universitário Estácio da Bahia','Estácio FIB'),
    ('Centro Universitário Estácio do Ceará','Estácio FIC'),
    ('Centro Universitário Euro-Americano','Unieuro'),
    ('Centro Universitário Faesa','Faesa'),
    ('Centro Universitário FAMETRO','CEUNI-FAMETRO'),
    ('Centro Universitário FIEO','Unifieo'),
    ('Centro Universitário Fluminense','Uniflu'),
    ('Centro Universitário Franciscano','Unifra'),
    ('Centro Universitário Fundação Educacional de Guaxupé','Unifeg'),
    ('Centro Universitário Geraldo Di Biase','UGB'),
    ('Centro Universitário Ibero-Americano','Unibero'),
    ('Centro Universitário Ibmec','IBMEC'),
    ('Centro Universitário INTA','Uninta'),
    ('Centro Universitário Internacional Uninter','Uninter'),
    ('Centro Universitário Jorge Amado','Unijorge'),
    ('Centro Universitário Leonardo da Vinci - Uniasselvi','Uniasselvi'),
    ('Centro Universitário Luterano de Ji-Paraná','Ceulji/Ulbra'),
    ('Centro Universitário Luterano de Palmas','Ulbra'),
    ('Centro Universitário Maurício de Nassau','Uninassau - Recife'),
    ('Centro Universitário Metodista do IPA','Metodista do Sul'),
    ('Centro Universitário Metodista Izabela Hendrix','IMIH'),
    ('Centro Universitário Moacyr Sreder Bastos','UniMSB'),
    ('Centro Universitário Monte Serrat','Unimonte'),
    ('Centro Universitário Moura Lacerda','Culm'),
    ('Centro Universitário Módulo','Módulo'),
    ('Centro Universitário Newton Paiva','Newtonpaiva'),
    ('Centro Universitário Nossa Senhora do Patrocínio','Ceunsp'),
    ('Centro Universitário Nove de Julho','Uninove'),
    ('Centro Universitário Padre Anchieta','UniAnchieta'),
    ('Centro Universitário Planalto do Distrito Federal','Uniplan'),
    ('Centro Universitário Plínio Leite','Unipli'),
    ('Centro Universitário Radial','Radial'),
    ('Centro Universitário Ritter dos Reis','Uniritter'),
    ('Centro Universitário Sagrado Coração','USC'),
    ('Centro Universitário Salesiano de São Paulo','Unisal'),
    ('Centro Universitário Santanna','Unisantanna'),
    ('Centro Universitário São Camilo','Cusc'),
    ('Centro Universitário São José de Itaperuna','FSJ'),
    ('Centro Universitário Tabosa de Almeida','ASCES-Unita'),
    ('Centro Universitário Tiradentes','UNIT'),
    ('Centro Universitário Toledo','Unitoledo'),
    ('Centro Universitário UNA','UNA'),
    ('Centro Universitário Unifacvest','Facvest'),
    ('Centro Universitário Unifanor Wyden','UniFavor'),
    ('Centro Universitário Unirg','Unirg'),
    ('Centro Universitário Univates','Univates'),
    ('Centro Universitário Univel','Univel'),
    ('Centro Universitário Universus Veritas','Univeritas'),
    ('Centro Universtário Uniseb','Uniseb'),
    ('Centro Univesitário La Salle','Unilasalle'),
    ('Claretiano - Faculdade','CLA'),
    ('Educação Corporativa','Educ'),
    ('Escola Federal de Engenharia de Itajubá','Efei'),
    ('Escola Superior de Administração, Marketing e Comunicação','Esamc'),
    ('Escola Superior de Administração, Marketing e Comunicação de Goiânia','Esamc de Goiânia'),
    ('Escola Superior de Administração, Marketing e Comunicação de Perdizes','Esamc Perdizes'),
    ('Escola Superior de Administração, Marketing e Comunicação de Salvador','Facoc Salvador'),
    ('Escola Superior de Administração, Marketing e Comunicação de Santos','Esamc Santos'),
    ('Escola Superior de Administração, Marketing e Comunicação de Sorocaba','Esamc Sorocaba'),
    ('Escola Superior de Estudos Empresariais e Informática','Eseei'),
    ('Escola Superior de Marketing','ESM'),
    ('Escola Superior de Propaganda e Marketing','ESPM-SP'),
    ('Escola Superior de Propaganda e Marketing','ESPM-RS'),
    ('Escola Superior de Relações Públicas','Esurp'),
    ('Estácio - Uniradial - Unidade Cotia','Estácio'),
    ('Faculdade Martha Falcão','FMF'),
    ('Faculdade 2 de Julho','F2J'),
    ('Faculdade Adventista de Hortolândia','Unasp - HT'),
    ('Faculdade Alagoana de Administração','FAA'),
    ('Faculdade Alves Faria','Alfa GO'),
    ('Faculdade Alvorada de Tecnologia e Educação de Maringá','Alvorada Maringá'),
    ('Faculdade Anhanguera de Anápolis','Anhanguera Anápolis'),
    ('Faculdade Anhanguera de Campinas','Anhanguera Campinas'),
    ('Faculdade Anhanguera de Jacareí','Anhanguera Jacareí'),
    ('Faculdade Anhanguera de Jundiaí','Anhanguera Jundiaí'),
    ('Faculdade Anhanguera de Limeira','Anhanguera Limeira'),
    ('Faculdade Anhanguera de Piracicaba','Anhanguera Piracicab'),
    ('Faculdade Anhanguera de Santa Bárbara d’Oeste','Anhanguera S B Oeste'),
    ('Faculdade Anhanguera de Taboão da Serra','Anhanguera-Taboão'),
    ('Faculdade Anhanguera de Taubaté','Anhanguera Taubaté'),
    ('Faculdade Anhanguera de Valinhos','Anhanguera Valinhos'),
    ('Faculdade Anhangüera de São José','Anhanguera São José'),
    ('Faculdade Anísio Teixeira de Feira de Santana','FAT'),
    ('Faculdade Araguaia','Fara'),
    ('Faculdade Asa de Brumadinho','ASA'),
    ('Faculdade Associada Brasil','FAB'),
    ('Faculdade Atenas Maranhense','Fama'),
    ('Faculdade Atual da Amazônia','FAA'),
    ('Faculdade Bandeirantes','Faban'),
    ('Faculdade Bandeirantes de Ciências Exatas e Humanas','Facex'),
    ('Faculdade Batista','Fabavi'),
    ('Faculdade Boa Viagem','FBV'),
    ('Faculdade Boas Novas','FBN'),
    ('Faculdade Boas Novas de Ciências Teológicas, Sociais e Biotecnológicas','FBNCTSB'),
    ('Faculdade Brasileira de Ciências Exatas, Humanas e Sociais','Fabrai'),
    ('Faculdade Brasileira de Informática','Fabrai'),
    ('Faculdade Cambury','Cambury'),
    ('Faculdade Campo Limpo Paulista','Faccamp'),
    ('Faculdade Canção Nova','FCN'),
    ('Faculdade Casper Líbero','Facasper'),
    ('Faculdade Cathedral','Facisa'),
    ('Faculdade Católica de Uberlândia','Católica'),
    ('Faculdade Católica do Ceará','FCC'),
    ('Faculdade Cearense','FaC'),
    ('Faculdade Cenecista de Bento Gonçalves','FACEBG'),
    ('Faculdade Cenecista de Bento Gonçalves','CNECBento'),
    ('Faculdade Cenecista de Capivari','Facecap'),
    ('Faculdade Cenecista de Rondonópolis','Facer'),
    ('Faculdade Cenecista de Sinop','Facenop'),
    ('Faculdade Cidade do Salvador','FCS'),
    ('Faculdade Cristo Rei','FacCRei'),
    ('Faculdade da Cidade de União da Vitória','Face'),
    ('Faculdade das Américas','FAM'),
    ('Faculdade de Administração, Comércio Exterior e Marketing de Vila Velha','Univila'),
    ('Faculdade de Americana','FAM'),
    ('Faculdade de Artes do Paraná','FAP'),
    ('Faculdade de Belas Artes','Febasp'),
    ('Faculdade de Belém','Fabel'),
    ('Faculdade de Castelo','FaCastelo'),
    ('Faculdade de Ciências e Administração de Petrolina','Facape'),
    ('Faculdade de Ciências Econômicas','Facamp'),
    ('Faculdade de Ciências Humanas de Pedro Leopoldo','FCHPL'),
    ('Faculdade de Ciências Humanas e Jurídicas de Teresina','Faculdade Ceut'),
    ('Faculdade de Ciências Humanas, Exatas e Letras de Rondônia','Faro'),
    ('Faculdade de Ciências Jurídicas e Sociais Aplicadas Rio Branco','Firb'),
    ('Faculdade de Ciências Jurídicas e Sociais Vianna Júnior','FCJSVJ'),
    ('Faculdade de Ciências Sociais Aplicadas','Facisa'),
    ('Faculdade de Comunicação Social de Passos','Facomp'),
    ('Faculdade de Ensino Superior da Cidade de Feira de Santana','Faesf/Unef'),
    ('Faculdade de Estudos Avançados do Pará','Feapa'),
    ('Faculdade de Excelência Educacional do Rio Grande do Norte','Fatern'),
    ('Faculdade de Filosofia, Ciências e Letras de Caruaru','Fafica'),
    ('Faculdade de Jaguariúna','FAJ'),
    ('Faculdade de Pato Branco','Fadep'),
    ('Faculdade de Pernambuco','Fape'),
    ('Faculdade de Presidente Prudente','Fapepe'),
    ('Faculdade de Tecnologia e Ciências de Itabuna','FTC Itabuna'),
    ('Faculdade de Tecnologia e Ciências de Jequié','FTC Jequié'),
    ('Faculdade de Tecnologia e Ciências de Salvador','FTC Salvador'),
    ('Faculdade de Tecnologia e Ciências de Vitória da Conquista','FTC - Vitória da Con'),
    ('Faculdade de Turismo da Bahia','Factur'),
    ('Faculdade de Valinhos','FAV'),
    ('Faculdade de Viçosa','FDV'),
    ('Faculdade Delta','FacDelta'),
    ('Faculdade do Acre','FAC'),
    ('Faculdade do Centro Leste','UCL'),
    ('Faculdade do Espírito Santo','Faesa'),
    ('Faculdade do Norte Novo de Apucarana','Facnopar'),
    ('Faculdade do Norte Pioneiro','Fanorpi'),
    ('Faculdade do Povo','FAPSP'),
    ('Faculdade do Sul','Facsul'),
    ('Faculdade do Sul - Unime Itabuna','Unimeitb'),
    ('Faculdade do Sul da Bahia','Fasb'),
    ('Faculdade do Vale do Itajaí Mirim','Favim'),
    ('Faculdade Dois de Julho','F2J'),
    ('Faculdade Eça de Queiros','Faceq'),
    ('Faculdade Eduvale de Avaré','Eduvale'),
    ('Faculdade Eniac','Eniac'),
    ('Faculdade Estadual de Ciências e Letras de Campo Mourão','Fecilcam'),
    ('Faculdade Estadual de Educação, Ciências e Letras do Paraná','Fafipa'),
    ('Faculdade Estadual de Filosofia, Ciências e Letras de União da Vitória','Fafiuv'),
    ('Faculdade Estácio de Sá','FESMS'),
    ('Faculdade Estácio de Sá de Belo Horizonte','FESBH'),
    ('Faculdade Estácio de Sá de Juiz de Fora','FESJF'),
    ('Faculdade Estácio de Sá de Santa Catarina','FESSC'),
    ('Faculdade Estácio de Sá de Vitória','Fesv'),
    ('Faculdade Estácio de São Luiz','ESTÁCIO DE SÃO LUIZ'),
    ('Faculdade Estácio do Rio Grande do Norte- Estácio FATERN','FATERN'),
    ('Faculdade Estácio FAP','FAP'),
    ('Faculdade Euro-Americana','Unieuro'),
    ('Faculdade Evolutivo','Face'),
    ('Faculdade Fucapi','Fucapi'),
    ('Faculdade Hélio Rocha','FHR'),
    ('Faculdade IELUSC','Ielusc'),
    ('Faculdade Integração Zona Oeste','Fizo'),
    ('Faculdade Integrada da Grande Fortaleza','FGF'),
    ('Faculdade Integradas Anhanguera','Fian'),
    ('Faculdade Integral Cantareira','FIC'),
    ('Faculdade Integral Diferencial','Facid'),
    ('Faculdade Interamericana de Porto Velho','Uniron'),
    ('Faculdade Internacional da Paraíba','FPB'),
    ('Faculdade Ipiranga','FA'),
    ('Faculdade JK/Anhanguera','JK/Anhanguera'),
    ('Faculdade Joaquim Nabuco - Paulista','FJN - Paulista'),
    ('Faculdade Joaquim Nabuco - Recife','FJN - Recife'),
    ('Faculdade Juvêncio Terra','FJT'),
    ('Faculdade Luterana São Marcos','Falsm'),
    ('Faculdade Maringá','Cespar'),
    ('Faculdade Marista','FMR'),
    ('Faculdade Maurício de Nassau','FMN'),
    ('Faculdade Maurício de Nassau de Maceió','Maurício de Nassau'),
    ('Faculdade Metodista Granbery','Granbery'),
    ('Faculdade Metropolitana da Grande Recife','Unesj'),
    ('Faculdade Metropolitana de Blumenau - Fameblu/Uniasselvi','Fameblu/Uniasselvi'),
    ('Faculdade Metropolitana de Guaramirim','Fameg'),
    ('Faculdade metropolitana de Maringá','Unifamma'),
    ('Faculdade Metropolitana do Amazonas','Fametro'),
    ('Faculdade Nacional','Finac'),
    ('Faculdade Oswaldo Cruz','FOC'),
    ('Faculdade Palas Atena','FPA'),
    ('Faculdade Pan Amazônica','Fapan'),
    ('Faculdade Paraense de Ensino','Fapen'),
    ('Faculdade Paulista de Comunicação','FPAC'),
    ('Faculdade Paulus de Tecnologia e Comunicação','Fapcom'),
    ('Faculdade Pernambucana','Fape'),
    ('Faculdade Pinheiro Guimarães','FAPG'),
    ('Faculdade Pio Décimo','FPD'),
    ('Faculdade Pitágoras - Unidade Guarapari','Facom'),
    ('Faculdade Pitágoras de Belo Horizonte','Pitágoras BH'),
    ('Faculdade Pitágoras de Londrina','FPL'),
    ('Faculdade Pitágoras de São Luís','Pitágoras S. Luís'),
    ('Faculdade Projeção','Projeção'),
    ('Faculdade Promove','Promove'),
    ('Faculdade Prudente de Moraes','FPM'),
    ('Faculdade Regional da Bahia','Farb'),
    ('Faculdade Reinaldo Ramos','Farr'),
    ('Faculdade Renascença','Uniesp'),
    ('Faculdade Ruy Barbosa','FRB'),
    ('Faculdade Salesiana de Vitória','Salesiana'),
    ('Faculdade Salesiana Maria Auxiliadora','FSMA'),
    ('Faculdade Santa Marcelina','Fasm'),
    ('Faculdade Santo Agostinho','FSA'),
    ('Faculdade Sapiens','Faculdade Sapiens'),
    ('Faculdade Satc','Satc'),
    ('Faculdade São Francisco de Barreiras','Fasb'),
    ('Faculdade São Francisco de Juazeiro','Fasj'),
    ('Faculdade São Francisco de Juazeiro','FASJ'),
    ('Faculdade São Luís','FSL'),
    ('Faculdade São Tomaz de Aquino','FSTA'),
    ('Faculdade Seama','Seama'),
    ('Faculdade Secal','Secal'),
    ('Faculdade Senac','Senac'),
    ('Faculdade Social da Bahia','FSBA'),
    ('Faculdade Sul-Americana','Fasam'),
    ('Faculdade Sumaré','Ises'),
    ('Faculdade Triângulo Mineiro','FTM'),
    ('Faculdade Ubaense Ozanam Coelho','Fagoc'),
    ('Faculdade União Bandeirante','Uniban'),
    ('Faculdade Unime de Ciências Sociais','FCS'),
    ('Faculdade Vasco da Gama','FVG'),
    ('Faculdades Atibaia','Faat'),
    ('Faculdades Campo Real','Camporeal'),
    ('Faculdades Cearense','FAC'),
    ('Faculdades COC','COC'),
    ('Faculdades de Campinas','Facamp'),
    ('Faculdades do Brasil','UniBrasil'),
    ('Faculdades do Oeste de Minas Gerais','Fadom'),
    ('Faculdades Guarapuava','Fac. Guarapuava'),
    ('Faculdades Hoyler','Uniesp'),
    ('Faculdades Integradas Alcântara Machado','Fiam-Faam'),
    ('Faculdades Integradas Assesc','Assesc'),
    ('Faculdades Integradas Barros Melo','Fibam'),
    ('Faculdades Integradas Cândido Rondon','Unirondon'),
    ('Faculdades Integradas Curitiba','FIC'),
    ('Faculdades Integradas da Bahia','FIB'),
    ('Faculdades Integradas da Upis','Upis'),
    ('Faculdades Integradas de Botucatu','Unifac'),
    ('Faculdades Integradas de Fernandópolis','Fife'),
    ('Faculdades Integradas de Jahu','FIJ'),
    ('Faculdades Integradas de Patos','FIP'),
    ('Faculdades Integradas de Rondonópolis','Fair'),
    ('Faculdades Integradas de Taquara','Faccat'),
    ('Faculdades Integradas de Três Lagoas','AEMS'),
    ('Faculdades Integradas de Várzea Grande','Fiavec'),
    ('Faculdades Integradas de Vitória','FDV'),
    ('Faculdades Integradas do Norte de Minas','Funorte'),
    ('Faculdades Integradas do Recife','FIR'),
    ('Faculdades Integradas do Tapajós','FIT'),
    ('Faculdades Integradas Facvest','Facvest'),
    ('Faculdades Integradas Facvest','Facvest'),
    ('Faculdades Integradas Hélio Alonso','Facha'),
    ('Faculdades Integradas IPEP','IPEP'),
    ('Faculdades Integradas Metropolitanas de Campinas','Metrocamp'),
    ('Faculdades Integradas Pitágoras','FIP-MOC'),
    ('Faculdades Integradas Rio Branco','FRB'),
    ('Faculdades Integradas Ritter dos Reis','UniRitter'),
    ('Faculdades Integradas Teresa D´Ávila','Fatea'),
    ('Faculdades Integradas Unicesp','Facicesp'),
    ('Faculdades Integrades Tiradentes','FITS'),
    ('Faculdades Luiz Meneghel','Falm'),
    ('Faculdades Nordeste','Fanor'),
    ('Faculdades Opet','Opet'),
    ('Faculdades Tancredo Neves','FTN'),
    ('FAE Centro Universitário do Paraná','FAE'),
    ('Fiam-Faam - Centro Universitário','Unifiam-Faam'),
    ('Fundação Armando Álvares Penteado','Faap'),
    ('Fundação Cesgranrio','Cesgranrio'),
    ('Fundação de Ensino Octávio Bastos','Feob'),
    ('Fundação de Ensino Superior de Passos','Fesp'),
    ('Fundação de Ensino Superior de São João Del Rei','Funrei'),
    ('Fundação Educacional de Brusque','Febe'),
    ('Fundação Educacional Serra dos Órgãos','Feso'),
    ('Fundação Escola de Comércio Álvares Penteado','Fecap'),
    ('Fundação Getúlio Vargas','FGV RJ'),
    ('Fundação Getúlio Vargas','FGV SP'),
    ('Fundação Mineira de Educação e Cultura','Fumec'),
    ('Fundação Novo Milênio','FNM'),
    ('Fundação Visconde de Cairu','FVC'),
    ('IDEA - Instituto de Desenvolvimento Educacional Avançado','Esamc-Uberlândia'),
    ('Instituto Baiano de Ensino Superior','Ibes'),
    ('Instituto Belo Horizonte de Ensino Superior','Ibhes'),
    ('Instituto Blumenauense de Ensino Superior','Ibes'),
    ('Instituto Cuiabá de Ensino e Cultura','Icec'),
    ('Instituto de Educação Superior da Paraíba','Iesp'),
    ('Instituto de Educação Superior de Brasília','Iesb'),
    ('Instituto de Educação Superior Raimundo Sá','IESRSA'),
    ('Instituto de Educação Superior São Francisco de Assis de Teófilo Otoni','Iesfato'),
    ('Instituto de Ensino e Cultura do Paraná','IECP'),
    ('Instituto de Ensino Superior','Fucapi'),
    ('Instituto de Ensino Superior Coc','COC'),
    ('Instituto de Ensino Superior de Alagoas','Iesa'),
    ('Instituto de Ensino Superior de Curitiba','Iesc'),
    ('Instituto de Ensino Superior de João Monlevade','Funcec'),
    ('Instituto de Ensino Superior de Olinda','Ieso'),
    ('Instituto de Ensino Superior de Rio Verde','Iesriver'),
    ('Instituto de Ensino Superior de Teresina','Iest'),
    ('Instituto de Ensino Superior do Maranhão','Iesma'),
    ('Instituto de Ensino Superior do Pará','Iesp'),
    ('Instituto de Ensino Superior e Formação Avançada de Vitória','Favi'),
    ('Instituto de Ensino Superior e Pesquisa de Divinópolis','Funedi'),
    ('Instituto de Estudos Superiores da Amazônia','Iesam'),
    ('Instituto Esperança de Ensino Superior','Iespes'),
    ('Instituto Federal de Educação, Ciência e Tecnologia do Sul de MG','IFSULDEMINAS'),
    ('Instituto Federal de Educação, Ciência e Tecnologia do Sul de Minas Gerais','IFSULDEMINAS'),
    ('Instituto Federal do Amazonas','Ifam'),
    ('Instituto Juiz de Fora de Ensino Superior','IJF'),
    ('Instituto Maceió de Ensino e Cultura','Imec'),
    ('Instituto Maranhense de Ensino e Cultura','Imec'),
    ('Instituto Municipal de Ensino Superior de Assis','Imesa'),
    ('Instituto Municipal de Ensino Superior de Bebedouro','Imesb'),
    ('Instituto Municipal de Ensino Superior de Catanduva','Imes Catanduva'),
    ('Instituto Natalense de Ensino e Cultura','Inec'),
    ('Instituto Paraibano de Ensino Renovado','Inper'),
    ('Instituto Paraíba de Educação e Cultura','Ipec'),
    ('Instituto Rio Branco','IRBR'),
    ('Instituto Sudeste Mineiro de Educação e Cultura','Ismec'),
    ('Instituto Superior de Ciências Aplicadas','Isca'),
    ('Instututo Infnet no Rio de Janeiro','Infnet'),
    ('Pontifícia Universidade Católica de Campinas','PUCCamp'),
    ('Pontifícia Universidade Católica de Goiás','PUCGO'),
    ('Pontifícia Universidade Católica de Minas Gerais','PUCMinas'),
    ('Pontifícia Universidade Católica de Minas Gerais (Arcos)','PUCArcos'),
    ('Pontifícia Universidade Católica de Minas Gerais - Poços de Caldas','Pucpcaldas'),
    ('Pontifícia Universidade Católica de São Paulo','PUCSP'),
    ('Pontifícia Universidade Católica do Paraná','PUCPR'),
    ('Pontifícia Universidade Católica do Rio de Janeiro','PUCRJ'),
    ('Pontifícia Universidade Católica do Rio Grande do Sul','PUCRS'),
    ('Sistema Universitário Prova por Área','Supra'),
    ('Sociedade de Educação e Cultura de Goiás','Fara'),
    ('União das Escolas Superiores de Cacoal','Unesc'),
    ('União das Faculdades dos Grandes Lagos','Unilago'),
    ('União de Escolas de Ensino Superior Capixaba','Unesc'),
    ('União Educacional de Brasília','Uneb'),
    ('União Educacional do Norte','Uninorte'),
    ('União Metropolitana de Educação e Cultura','Unime'),
    ('UniBrasil Centro Universitário','UniBrasil'),
    ('Unidade de Ensino Superior de Feira de Santana','Unef'),
    ('Unidade de Ensino Superior Vale do Iguaçu','Uniguaçu'),
    ('Univag - Centro Universitário','Univag'),
    ('Universidade Anhanguera-Uniderp','Uniderp'),
    ('Universidade Anhembi Morumbi','UAM'),
    ('Universidade Bandeirante de São Paulo','Uniban'),
    ('Universidade Braz Cubas','UBC'),
    ('Universidade Castelo Branco','UCB'),
    ('Universidade Católica de Brasília','UCB'),
    ('Universidade Católica de Goiás','UCG'),
    ('Universidade Católica de Pelotas','UCPel'),
    ('Universidade Católica de Pernambuco','Unicap'),
    ('Universidade Católica de Petrópolis','UCP'),
    ('Universidade Católica de Santos','UniSantos'),
    ('Universidade Católica do Salvador','Ucsal'),
    ('Universidade Católica Dom Bosco','UCDB'),
    ('Universidade Cândido Mendes','UCAM'),
    ('Universidade Cidade São Paulo','Unicid'),
    ('Universidade Comunitária da Região de Chapecó','Unochapecó'),
    ('Universidade Cruzeiro do Sul','Unicsul'),
    ('Universidade da Amazônia','Unama'),
    ('Universidade da Regiao da Campanha','Urcamp'),
    ('Universidade da Região de Joinville','Univille'),
    ('Universidade de Alfenas','Unifenas'),
    ('Universidade de Brasília','UnB'),
    ('Universidade de Caxias do Sul','UCS'),
    ('Universidade de Cruz Alta','Unicruz'),
    ('Universidade de Cuiabá','Unic'),
    ('Universidade de Fortaleza','Unifor'),
    ('Universidade de Franca','Unifran'),
    ('Universidade de Guarulhos','UNG'),
    ('Universidade de Marília','Unimar'),
    ('Universidade de Mogi das Cruzes','UMC'),
    ('Universidade de Montes Claros','Unimontes'),
    ('Universidade de Passo Fundo','UPF'),
    ('Universidade de Pernambuco','UPE'),
    ('Universidade de Ribeirão Preto','Unaerp'),
    ('Universidade de Santa Cruz do Sul','Unisc'),
    ('Universidade de São Paulo','USP'),
    ('Universidade de Sorocaba','Uniso'),
    ('Universidade de Taubaté','Unitau'),
    ('Universidade de Teste','Uniteste'),
    ('Universidade de Três Corações','Unincor'),
    ('Universidade de Uberaba','Uniube'),
    ('Universidade de Uberaba','Uniube'),
    ('Universidade do Centro do Paraná','UCP'),
    ('Universidade do Contestado','UnC'),
    ('Universidade do Estado da Bahia - Campus Conceição do Coité','Uneb-Conceição'),
    ('Universidade do Estado da Bahia - Campus Juazeiro','Uneb-Juazeiro'),
    ('Universidade do Estado da Bahia - Campus Salvador','Uneb-Salvador'),
    ('Universidade do Estado da Bahia - Campus Seabra','Uneb-Seabra'),
    ('Universidade do Estado de Mato Grosso','Unemat'),
    ('Universidade do Estado de Minas Gerais','UEMG'),
    ('Universidade do Estado de Santa Catarina','Udesc'),
    ('Universidade do Estado do Rio de Janeiro','Uerj'),
    ('Universidade do Estado do Rio Grande do Norte','Uern'),
    ('Universidade do Grande ABC','Uniabc'),
    ('Universidade do Grande Rio','Unigranrio'),
    ('Universidade do Oeste de Santa Catarina','Unoesc'),
    ('Universidade do Oeste de Santa Catarina - Joaçaba','Unoesc - Joaçaba'),
    ('Universidade do Oeste Paulista','Unoeste'),
    ('Universidade do Sul de Santa Catarina','Unisul'),
    ('Universidade do Tocantins','Unitins'),
    ('Universidade do Vale do Itajaí','Univali'),
    ('Universidade do Vale do Paraíba','UNIVAP'),
    ('Universidade do Vale do Rio dos Sinos','Unisinos'),
    ('Universidade do Vale do Sapucaí','Univás'),
    ('Universidade Estadual da Paraíba','UEPB'),
    ('Universidade Estadual de Campinas','Unicamp'),
    ('Universidade Estadual de Feira de Santana','UEFS'),
    ('Universidade Estadual de Goiás','UEG'),
    ('Universidade Estadual de Londrina','UEL'),
    ('Universidade Estadual de Maringá','UEM'),
    ('Universidade Estadual de Mato Grosso do Sul','UEMS'),
    ('Universidade Estadual de Ponta Grossa','UEPG'),
    ('Universidade Estadual de Santa Cruz','Uesc'),
    ('Universidade Estadual do Ceará','Uece'),
    ('Universidade Estadual do Centro-Oeste','Unicentro'),
    ('Universidade Estadual do Maranhão','Uema'),
    ('Universidade Estadual do Oeste do Paraná','Unioeste'),
    ('Universidade Estadual do Pará','Uepa'),
    ('Universidade Estadual do Piauí','Uespi'),
    ('Universidade Estadual do Rio Grande do Norte','Uern'),
    ('Universidade Estadual do Sudoeste da Bahia','Uesb'),
    ('Universidade Estadual Paulista','Unesp'),
    ('Universidade Estadual Vale do Aracaú','UVA'),
    ('Universidade Estácio de Sá','Unesa'),
    ('Universidade Federal da Bahia','UFBA'),
    ('Universidade Federal da Paraíba','UFPB'),
    ('Universidade Federal de Alagoas','Ufal'),
    ('Universidade Federal de Campina Grande','UFCG'),
    ('Universidade Federal de Goiás','UFG'),
    ('Universidade Federal de Juiz de Fora','UFJF'),
    ('Universidade Federal de Lavras','Ufla'),
    ('Universidade Federal de Mato Grosso','UFMT'),
    ('Universidade Federal de Mato Grosso - Araguaia','UFMT-Araguaia'),
    ('Universidade Federal de Mato Grosso do Sul','UFMS'),
    ('Universidade Federal de Minas Gerais','UFMG'),
    ('Universidade Federal de Ouro Preto','Ufop'),
    ('Universidade Federal de Pelotas','UFPel'),
    ('Universidade Federal de Pernambuco','UFPE'),
    ('Universidade Federal de Pernambuco - Caruaru','UFPE-Caruaru'),
    ('Universidade Federal de Rondônia','Unir'),
    ('Universidade Federal de Roraima','UFRR'),
    ('Universidade Federal de Santa Catarina','UFSC'),
    ('Universidade Federal de Santa Maria','UFSM'),
    ('Universidade Federal de Santa Maria - Frederico Westphallen','UFSM-FW'),
    ('Universidade Federal de São Carlos','UFSCar'),
    ('Universidade Federal de São João del-Rei','UFSJ'),
    ('Universidade Federal de São Paulo','Unifiesp'),
    ('Universidade Federal de Sergipe','UFS'),
    ('Universidade Federal de Sergipe','UFS'),
    ('Universidade Federal de Uberlândia','UFU'),
    ('Universidade Federal de Viçosa','UFV'),
    ('Universidade Federal do Acre','Ufac'),
    ('Universidade Federal do Amapá','Unifap'),
    ('Universidade Federal do Amazonas','Ufam'),
    ('Universidade Federal do Amazonas - Parintins','Ufam - Parintins'),
    ('Universidade Federal do Cariri','UFCA'),
    ('Universidade Federal do Ceará','UFC'),
    ('Universidade Federal do Espírito Santo','Ufes'),
    ('Universidade Federal do Maranhão','UFMA'),
    ('Universidade Federal do Maranhão - Imperatriz','Ufma - Imperatriz'),
    ('Universidade Federal do Mato Grosso - Barra do Garça','UFMT-Barra do Garça'),
    ('Universidade Federal do Pampa','Unipampa'),
    ('Universidade Federal do Paraná','UFPR'),
    ('Universidade Federal do Pará','UFPA'),
    ('Universidade Federal do Piauí','UFPI'),
    ('Universidade Federal do Recôncavo da Bahia','UFRB'),
    ('Universidade Federal do Rio de Janeiro','UFRJ'),
    ('Universidade Federal do Rio Grande do Norte','UFRN'),
    ('Universidade Federal do Rio Grande do Sul','UFRGS'),
    ('Universidade Federal do Sul e Sudeste do Pará','Unifesspa'),
    ('Universidade Federal do Tocantins','UFT'),
    ('Universidade Federal Fluminense','UFF'),
    ('Universidade Federal Rural do Rio de Janeiro','UFRRJ'),
    ('Universidade Feevale','Feevale'),
    ('Universidade Fumec','Fumec'),
    ('Universidade Gama Filho','UGF'),
    ('Universidade Ibirapuera','UNIb'),
    ('Universidade Luterana do Brasil','Ulbra'),
    ('Universidade Metodista de Piracicaba','Unimep'),
    ('Universidade Metodista de São Paulo','Umesp'),
    ('Universidade Municipal de São Caetano do Sul','USCS'),
    ('Universidade Nilton Lins','Niltonlins'),
    ('Universidade Norte do Paraná','Unopar'),
    ('Universidade para o Desenvolvimento do Alto Vale do Itajaí','Unidavi'),
    ('Universidade Paranaense','Unipar'),
    ('Universidade Paulista','Unip'),
    ('Universidade Paulista','UNIP-Brasília'),
    ('Universidade Positivo','UP'),
    ('Universidade Potiguar','UnP'),
    ('Universidade Presbiteriana Mackenzie','Mackenzie'),
    ('Universidade Presidente Antônio Carlos','Unipac'),
    ('Universidade Regional de Blumenau','Furb'),
    ('Universidade Regional do Cariri','Urca'),
    ('Universidade Regional do Noroeste do Estado do RS','Unijuí'),
    ('Universidade Regional Integrada do Alto do Uruguai','URI'),
    ('Universidade Salgado de Oliveira','Universo GO'),
    ('Universidade Salgado de Oliveira','Universo PE'),
    ('Universidade Salgado de Oliveira','Universo RJ'),
    ('Universidade Salvador','Unifacs'),
    ('Universidade Sant Anna','UniSant Anna'),
    ('Universidade Santa Cecília','Unisanta'),
    ('Universidade Santa Úrsula','USU'),
    ('Universidade Santo Amaro','Unisa'),
    ('Universidade São Francisco','USF'),
    ('Universidade São Judas Tadeu','USJT'),
    ('Universidade São Marcos','USM'),
    ('Universidade Severino Sombra','USS'),
    ('Universidade Tecnológica Federal do Paraná','UTFPR'),
    ('Universidade Tiradentes','Unit'),
    ('Universidade Tuiuti do Paraná','UTP'),
    ('Universidade Vale do Rio Doce','Univale'),
    ('Universidade Veiga de Almeida - Barra da Tijuca','UVA-Barra da Tijuca'),
    ('Universidade Veiga de Almeida - Cabo Frio','UVA-Cabo Frio'),
    ('Universidade Veiga de Almeida - Tijuca','UVA-Tijuca'),
    ('Universidade Vila Velha','UVV'),
    ('Veris Faculdades - Campinas','Veris');